
version: '3.5'

services:
  postgres:
    container_name: becomy_db
    image: postgres
    environment:
      POSTGRES_USER: becomy_db_user
      POSTGRES_PASSWORD: becomy_db_password
      POSTGRES_DB: becomy
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres: