version: "3.5"

services:
  becomy_web:
    container_name: becomy_web
    build: ./..
    ports:
      - "5005:8080"
    networks:
      - becomy
  postgres:
    container_name: becomy_db
    image: postgres
    environment:
      POSTGRES_USER: becomy_db_user
      POSTGRES_PASSWORD: becomy_db_password
      POSTGRES_DB: becomy
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - becomy

networks:
  becomy: {}

volumes:
  postgres:
