version: "3.5"

services:
  becomy_web:
    container_name: becomy_web
    build: ./..
    ports:
      - "5005:8080"
    networks:
      - becomy
    environment:
      - DATABASE_URL=postgresql://becomy_db_user:becomy_db_password@becomy_db:5432/becomy

  postgres_becomy:
    container_name: becomy_db
    image: postgres
    environment:
      POSTGRES_USER: becomy_db_user
      POSTGRES_PASSWORD: becomy_db_password
      POSTGRES_DB: becomy
      PGDATA: /data/postgres
    volumes:
      - postgres_becomy:/data/postgres
    ports:
      - "5006:5432"
    restart: unless-stopped
    networks:
      - becomy

networks:
  becomy: {}

volumes:
  postgres_becomy:
